export enum appTypes {
    CALL_PUBLIC_API_POST = "CALL_PUBLIC_API_POST",
    TRIGGER_ADD_TO_FAVORITE_LIST = "TRIGGER_ADD_TO_FAVORITE_LIST",
    CHECKING_AND_UNCHECKING_ITEMS = 'CHECKING_AND_UNCHECKING_ITEMS'
}